name: Build Debug APK

on:
  push:
    branches:
      - main  # ya jis branch par chahte ho
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: "33.0.2"
          ndk: "25.2.9519653"

      - name: Grant execute permission for gradlew
        run: chmod +x ./ChessChatApp/gradlew

      - name: Build Debug APK
        run: ./ChessChatApp/gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: ./ChessChatApp/app/build/outputs/apk/debug/app-debug.apk