name: Build Debug APK - Save Errors to Repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
        continue-on-error: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
        continue-on-error: true

      - name: Make gradlew executable
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
          else
            echo "gradlew file missing"
          fi
        continue-on-error: true

      - name: Build APK and save only errors
        run: |
          if [ -f ./gradlew ]; then
            ./gradlew assembleDebug 2> build_error.txt || true
          else
            echo "gradlew not found" > build_error.txt
          fi
        continue-on-error: true

      - name: Commit and push build_error.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add build_error.txt
          git commit -m "Update build_error.txt from workflow" || echo "No changes"
          git push origin HEAD
        continue-on-error: true