name: Build Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Make gradlew executable
        working-directory: ChessChatApp/ChessChatApp
        run: chmod +x gradlew

      - name: Build Debug APK
        working-directory: ChessChatApp/ChessChatApp
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ChessChatApp-debug-apk
          path: ChessChatApp/ChessChatApp/app/build/outputs/apk/debug/*.apk