name: Build Debug APK - Save Errors to Repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
        continue-on-error: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
        continue-on-error: true

      - name: Make gradlew executable
        run: chmod +x ./gradlew || true
        continue-on-error: true

      - name: Build APK and capture only errors to file
        run: |
          if [ -f ./gradlew ]; then
            ./gradlew assembleDebug 2> build_error.txt || true
          else
            echo "gradlew not found" > build_error.txt
          fi
        continue-on-error: true

      - name: Commit and push build_error.txt to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add build_error.txt
          git commit -m "Update build_error.txt from workflow" || echo "No changes to commit"
          git push origin HEAD || echo "Push failed"
        continue-on-error: true