name: Build Debug APK (Auto gradlew)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ensure Gradle wrapper exists and is executable
        working-directory: ChessChatApp/ChessChatApp
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "gradlew missing, attempting to generate wrapper..."
            # try to generate wrapper if gradle is available on runner
            gradle wrapper || echo "gradle not available on runner — please commit gradlew to repository"
          fi
          chmod +x ./gradlew || true

      - name: Build Debug APK
        working-directory: ChessChatApp/ChessChatApp
        run: |
          ./gradlew assembleDebug --no-daemon

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ChessChatApp-debug-apk
          path: ChessChatApp/ChessChatApp/app/build/outputs/apk/debug/*.apk          path: ChessChatApp/ChessChatApp/app/build/outputs/apk/debug/*.apk      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ChessChatApp-debug
          path: "ChessChatApp/ChessChatApp/app/build/outputs/apk/debug/*.apk"        run: |
          cd ChessChatApp/ChessChatApp
          ./gradlew assembleDebug

      # 5️⃣ Upload APK as artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ChessChatApp-debug
          path: "ChessChatApp/ChessChatApp/app/build/outputs/apk/debug/*.apk"          chmod +x ./gradlew

      # 5️⃣ Build Debug APK
      - name: Build Debug APK
        run: |
          cd ChessChatApp/ChessChatApp
          ./gradlew assembleDebug

      # 6️⃣ Upload APK as artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ChessChatApp-debug
          path: ChessChatApp/ChessChatApp/app/build/outputs/apk/debug/*.apk        run: |
          cd ChessChatApp
          if [ -f "./gradlew" ]; then
            ./gradlew assembleDebug
          else
            echo "⚠ gradlew not found, build will likely fail"
          fi

      # 5️⃣ Upload Debug APK as artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ChessChatApp-debug
          path: ChessChatApp/app/build/outputs/apk/debug/*.apk
