name: Debug Gradle Path

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug - Find gradlew path
        run: |
          python3 - << 'EOF' 2> error_log.txt
          import os
          try:
              found = False
              for root, dirs, files in os.walk('.'):
                  if 'gradlew' in files:
                      print(f"✅ gradlew found at: {os.path.join(root, 'gradlew')}")
                      found = True
              if not found:
                  print("gradlew not found.")
          except Exception as e:
              with open("error_log.txt", "w") as f:
                  f.write(str(e))
          print("Search complete.")
          EOF

      - name: Show error log if any
        if: failure()
        run: |
          echo "Errors captured in error_log.txt:"
          cat error_log.txt