name: Build Debug APK - Save Errors

on:
  workflow_run:
    workflows: ["Build Debug APK"]  # Workflow 1 ka exact name
    types:
      - completed
  workflow_dispatch:  # Manual trigger bhi allow

jobs:
  save_errors:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }} # Only run if build failed

    steps:
      - name: Checkout repo with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Get Workflow Run ID
        run: |
          echo "RUN_ID=${{ github.event.workflow_run.id }}" >> $GITHUB_ENV

      - name: Download Workflow Logs
        run: |
          curl -L -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -o workflow_logs.zip \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/logs
          unzip workflow_logs.zip -d workflow_logs

      - name: Extract Build Errors
        run: |
          # Clear previous error file if exists
          > build_error.txt
          # Extract only FAILURE or ERROR lines from gradle logs
          grep -i "FAILURE\|ERROR" workflow_logs/* > build_error.txt || true

      - name: Commit and Push Errors if Non-Empty
        run: |
          if [ -s build_error.txt ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add build_error.txt
            git commit -m "Update build_error.txt from latest workflow run" || echo "No changes"
            git push origin HEAD
          else
            echo "No errors found. Skipping push."
          fi
