name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run test commands
        run: |
          echo "This is a test workflow to trigger the log capture"
          echo "Running some test commands..."
          date
          echo "Test completed successfully!"
